# [ Plugins ]
# Tmux Plugin Manager's fork with async loading of plugins
set -g @plugin 'x3rAx/tpm-async'

# Plugin which adds custom nerd font icons to window names
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'lost-melody/tmux-command-palette'

# [ Source/Run Extra Files ]
# Source core options
source "./options.tmux"

# Source colorscheme configuration
source "./colorscheme.tmux"

# Source core keymaps
source "./keymaps.tmux"

# Initialize TPM
run -b '#{d:current_file}/plugins/tpm-async/tpm'

# Source file with configurations for plugins
source "./plugins.tmux"
