# [ Plugins ]
# tpm-async: Tmux Plugin Manager's fork with async loading
set -g @plugin 'x3rAx/tpm-async'

# tmux-nerd-font-window-name: Plugin which adds custom nerd font icons to window names
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

# Initialize Tmux Plugin Manager
run -b '#{d:current_file}/plugins/tpm-async/tpm'

# Variable to change accent color of tmux
# NOTE: Works because I configured my tmux to use it
set -g @thm_accent-color 'green'

# [ Server Options ]
source -qF '#{d:current_file}/server.tmux'

# [ Session Options ]
source -qF '#{d:current_file}/session.tmux'

# [ Window & Pane Options ]
source -qF '#{d:current_file}/window&pane.tmux'

# [ Keymaps ]
source -qF '#{d:current_file}/keymaps.tmux'
