# [ Plugins ]
# tpm-async: Tmux Plugin Manager's fork with async loading
set -g @plugin 'x3rAx/tpm-async'

# tmux-nerd-font-window-name: Plugin which adds custom nerd font icons to window names
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

# Initialize Termux Plugin Manager
run -b '#{d:current_file}/plugins/tpm-async/tpm'

# [ Colorscheme ]
# Catppuccin Mocha colors
set -g @thm_black '#11111B'
set -g @thm_grey '#45475A'
set -g @thm_white '#CDD6F4'
set -g @thm_red '#F38BA8'
set -g @thm_yellow '#F9E2AF'
set -g @thm_green '#A6E3A1'
set -g @thm_blue '#89B4FA'
set -g @thm_purple '#CBA6F7'
set -gqF @thm_foreground '#{@thm_white}'
set -g @thm_background '#1E1E2E'
set -gqF @thm_cursor-color '#{@thm_white}'
set -gqF @thm_accent-color '#{@thm_green}'

# [ Server Options ]
source -qF '#{d:current_file}/server.tmux'

# [ Session Options ]
source -qF '#{d:current_file}/session.tmux'

# [ Window & Pane Options ]
source -qF '#{d:current_file}/window&pane.tmux'

# [ Keymaps ]
source -qF '#{d:current_file}/keymaps.tmux'
