[base]
default          = 007
unknown-token    = 001,bold
commandseparator = 006
redirection      = 005
here-string-tri  = 003
here-string-text = 004
here-string-var  = 006,bg:004
exec-descriptor  = 003,bold
comment          = 008,bold
correct-subtle   = 004
incorrect-subtle = 001
subtle-separator = 002
subtle-bg        = 000,bg:004
secondary        = free
recursive-base   = 002

[command-point]
reserved-word     = 003
subcommand        = 003
alias             = 005
suffix-alias      = 005
global-alias      = 000,bg:005
builtin           = 002
function          = 005
command           = 002
precommand        = 005
hashed-command    = 002
single-sq-bracket = 006
double-sq-bracket = 006
double-paren      = 013

[paths]
path          = 004
pathseparator = 
path-to-dir   = 004,underline
globbing      = 004,bold
globbing-ext  = 013

[brackets]
paired-bracket  = 000,bg:004
bracket-level-1 = 002,bold
bracket-level-2 = 003,bold
bracket-level-3 = 004,bold

[arguments]
single-hyphen-option   = 006
double-hyphen-option   = 004
back-quoted-argument   = 002
single-quoted-argument = 002
double-quoted-argument = 002
dollar-quoted-argument = 003

[in-string]
; backslash in $'...'
back-dollar-quoted-argument = 006
; backslash or $... in "..."
back-or-dollar-double-quoted-argument = 006

[other]
variable             = 005,bold
assign               = 006
assign-array-bracket = 002
history-expansion    = 004,bold

[math]
mathvar = 005,bold
mathnum = 013
matherr = 001

[for-loop]
forvar    = 005
fornum    = 013
operator  = 002
foroper   = 003
separator = 006
forsep    = 003,bold

[case]
case-input       = 002
case-parentheses = 003
case-condition   = 000,bg:004

