[base]
default          = #CDD6F4
unknown-token    = #F38BA8,bold
commandseparator = #89DCEB
redirection      = #B4BEFE
here-string-tri  = #F9E2AF
here-string-text = #89B4FA
here-string-var  = #89DCEB,bg:#89B4FA
exec-descriptor  = #F9E2AF,bold
comment          = #6C7086,bold
correct-subtle   = #89B4FA
incorrect-subtle = #F38BA8
subtle-separator = #A6E3A1
subtle-bg        = #11111B,bg:#89B4FA
secondary        = free
recursive-base   = #A6E3A1

[command-point]
reserved-word     = #F9E2AF
subcommand        = #F9E2AF
alias             = #B4BEFE
suffix-alias      = #B4BEFE
global-alias      = #11111B,bg:#B4BEFE
builtin           = #A6E3A1
function          = #B4BEFE
command           = #A6E3A1
precommand        = #B4BEFE
hashed-command    = #A6E3A1
single-sq-bracket = #89DCEB
double-sq-bracket = #89DCEB
double-paren      = #F5C2E7

[paths]
path          = #89B4FA
pathseparator = 
path-to-dir   = #89B4FA,underline
globbing      = #89B4FA,bold
globbing-ext  = #F5C2E7

[brackets]
paired-bracket  = #11111B,bg:#89B4FA
bracket-level-1 = #A6E3A1,bold
bracket-level-2 = #F9E2AF,bold
bracket-level-3 = #89B4FA,bold

[arguments]
single-hyphen-option   = #89DCEB
double-hyphen-option   = #89DCEB
back-quoted-argument   = #A6E3A1
single-quoted-argument = #A6E3A1
double-quoted-argument = #A6E3A1
dollar-quoted-argument = #F9E2AF

[in-string]
; backslash in $'...'
back-dollar-quoted-argument = #89DCEB
; backslash or $... in "..."
back-or-dollar-double-quoted-argument = #89DCEB

[other]
variable             = #B4BEFE,bold
assign               = #89DCEB
assign-array-bracket = #A6E3A1
history-expansion    = #89B4FA,bold

[math]
mathvar = #B4BEFE,bold
mathnum = #F5C2E7
matherr = #F38BA8

[for-loop]
forvar    = #B4BEFE
fornum    = #F5C2E7
operator  = #A6E3A1
foroper   = #F9E2AF
separator = #89DCEB
forsep    = #F9E2AF,bold

[case]
case-input       = #A6E3A1
case-parentheses = #F9E2AF
case-condition   = #11111B,bg:#89B4FA

